# Generated by Django 4.2.7 on 2023-11-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(max_length=155),
        ),
    ]
